server:
  port: 8082
spring:
  application:
    name: ms-transacciones
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:mysql://localhost:3306/bancoxyz
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
