spring.datasource.url=jdbc:mysql://localhost:3306/bancoxyz
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always

# Orquestación aislada de Jobs:
# spring.batch.job.name=reporteDiarioJob
spring.batch.job.name=calculoInteresesJob
# spring.batch.job.name=estadoCuentaAnualJob


# Configuracion de Seguridad (HTTPS)
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=admin123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz