server:
  port: 9000
spring:
  application:
    name: auth-server
auth-server:
  issuer: ${AUTH_SERVER_ISSUER:http://localhost:9000}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/