server:
  port: 8445
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: admin123
    key-store-type: PKCS12
    key-alias: bancoxyz
spring:
  kafka:
    bootstrap-servers: localhost:29092 # Kafka centralizado para el productor
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Parámetros explícitos de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      coreServiceCB:
        slidingWindowSize: 5                  # Evalúa el porcentaje de fallo en las últimas 5 llamadas
        failureRateThreshold: 50              # Abre el circuito si el 50% de esas llamadas falla
        waitDurationInOpenState: 10000ms      # Mantiene el circuito abierto por 10 segundos antes de probar
        permittedNumberOfCallsInHalfOpenState: 2