server:
  port: 8082
spring:
  application:
    name: ms-transacciones
  datasource:
    url: jdbc:mysql://localhost:3306/bancoxyz
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Correccon de identacion
  kafka:
    bootstrap-servers: localhost:29092 # Kafka centralizado
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/